import React, { useState } from 'react';
import { Box, Button, TextField, Typography, Stepper, Step, StepLabel, Card, CardContent, FormControlLabel, Checkbox, FormControl, FormLabel, RadioGroup, Radio, MenuItem, Stack, Chip, InputAdornment, Alert } from '@mui/material';
import { AttachMoney, Upload, LocationOn, Person, Phone, Email } from '@mui/icons-material';

interface VasitaRomorkFormData {
  title: string; description: string; productionYear: string; hasDamper: boolean; isExchangeable: string; uploadedImages: File[]; price: string; priceType: string; currency: string; sellerPhone: string; sellerName: string; sellerEmail: string; city: string; district: string;
}

const steps = ['İlan Detayları', 'Fotoğraflar', 'İletişim & Fiyat'];

const VasitaRomorkForm: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);
  const [formData, setFormData] = useState<VasitaRomorkFormData>({
    title: '', description: '', productionYear: '', hasDamper: false, isExchangeable: '', uploadedImages: [], price: '', priceType: 'fixed', currency: 'TRY', sellerPhone: '', sellerName: '', sellerEmail: '', city: '', district: ''
  });

  const handleNext = () => setActiveStep((prev) => prev + 1);
  const handleBack = () => setActiveStep((prev) => prev - 1);
  const handleInputChange = (field: keyof VasitaRomorkFormData, value: any) => { setFormData(prev => ({ ...prev, [field]: value })); };
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const files = event.target.files; if (!files) return; const newFiles = Array.from(files); const totalFiles = formData.uploadedImages.length + newFiles.length; if (totalFiles > 10) { alert('En fazla 10 fotoğraf yükleyebilirsiniz.'); return; } setFormData(prev => ({ ...prev, uploadedImages: [...prev.uploadedImages, ...newFiles] })); };
  const removeImage = (index: number) => { setFormData(prev => ({ ...prev, uploadedImages: prev.uploadedImages.filter((_, i) => i !== index) })); };
  const generateYearOptions = () => { const currentYear = new Date().getFullYear(); const years = []; for (let year = currentYear; year >= currentYear - 30; year--) { years.push(year.toString()); } return years; };

  const renderStepContent = (step: number) => {
    switch (step) {
      case 0: return (<Card><CardContent><Typography variant="h6" gutterBottom>Vasıta Römorku İlan Detayları</Typography><TextField fullWidth label="İlan Başlığı" value={formData.title} onChange={(e) => handleInputChange('title', e.target.value)} margin="normal" required /><TextField fullWidth label="Açıklama" value={formData.description} onChange={(e) => handleInputChange('description', e.target.value)} margin="normal" multiline rows={4} required /><TextField select fullWidth label="Üretim Yılı" value={formData.productionYear} onChange={(e) => handleInputChange('productionYear', e.target.value)} margin="normal" required>{generateYearOptions().map((year) => (<MenuItem key={year} value={year}>{year}</MenuItem>))}</TextField><FormControlLabel control={<Checkbox checked={formData.hasDamper} onChange={(e) => handleInputChange('hasDamper', e.target.checked)} />} label="Damper" sx={{ mt: 2, mb: 2 }} /><FormControl component="fieldset" margin="normal" fullWidth><FormLabel component="legend">Takaslı</FormLabel><RadioGroup value={formData.isExchangeable} onChange={(e) => handleInputChange('isExchangeable', e.target.value)} row><FormControlLabel value="evet" control={<Radio />} label="Evet" /><FormControlLabel value="hayır" control={<Radio />} label="Hayır" /></RadioGroup></FormControl></CardContent></Card>);
      case 1: return (<Stack spacing={3}><Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}><Upload color="primary" />Fotoğraf Yükleme</Typography><Typography variant="body2" color="text.secondary">Aracınızın fotoğraflarını yükleyin (Maksimum 10 adet)</Typography><Card sx={{ border: '2px dashed #ddd', textAlign: 'center', p: 4 }}><CardContent><Upload sx={{ fontSize: 48, color: 'text.secondary', mb: 2 }} /><Typography variant="h6" gutterBottom>Fotoğraf Yükle</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>JPG, PNG formatında maksimum 5MB boyutunda dosyalar yükleyebilirsiniz</Typography><input accept="image/*" style={{ display: 'none' }} id="image-upload" multiple type="file" onChange={handleImageUpload} /><label htmlFor="image-upload"><Button variant="contained" component="span">Fotoğraf Seç</Button></label></CardContent></Card>{formData.uploadedImages.length > 0 && (<Box><Typography variant="subtitle1" sx={{ mb: 2 }}>Yüklenen Fotoğraflar ({formData.uploadedImages.length}/10)</Typography><Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 2 }}>{formData.uploadedImages.map((file, index) => (<Box key={index} sx={{ position: 'relative' }}><img src={URL.createObjectURL(file)} alt={`Upload ${index + 1}`} style={{ width: 120, height: 80, objectFit: 'cover', borderRadius: 8, border: index === 0 ? '2px solid #4CAF50' : '1px solid #ddd' }} />{index === 0 && <Chip label="Vitrin" color="success" size="small" sx={{ position: 'absolute', top: 4, left: 4 }} />}<Button size="small" color="error" onClick={() => removeImage(index)} sx={{ position: 'absolute', top: 4, right: 4, minWidth: 24, width: 24, height: 24, p: 0, bgcolor: 'rgba(255,255,255,0.8)' }}>×</Button></Box>))}</Box></Box>)}<Typography variant="body2" color="text.secondary">💡 İpucu: İlk yüklediğiniz fotoğraf vitrin fotoğrafı olarak kullanılacaktır</Typography></Stack>);
      case 2: return (<Stack spacing={3}><Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}><AttachMoney color="primary" />Fiyat ve İletişim Bilgileri</Typography><Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}><TextField sx={{ flex: 1, minWidth: 200 }} label="Fiyat" value={formData.price} onChange={(e) => handleInputChange('price', e.target.value)} placeholder="Örn: 450.000" InputProps={{ startAdornment: <InputAdornment position="start">₺</InputAdornment> }} required /><TextField sx={{ flex: 1, minWidth: 200 }} label="İl" value={formData.city} onChange={(e) => handleInputChange('city', e.target.value)} placeholder="Şehir" InputProps={{ startAdornment: <InputAdornment position="start"><LocationOn /></InputAdornment> }} required /></Box><TextField fullWidth label="İlçe" value={formData.district} onChange={(e) => handleInputChange('district', e.target.value)} placeholder="İlçe" InputProps={{ startAdornment: <InputAdornment position="start"><LocationOn /></InputAdornment> }} required /><Typography variant="subtitle1" sx={{ fontWeight: 'bold' }}>📞 İletişim Bilgileri</Typography><Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}><TextField sx={{ flex: 1, minWidth: 200 }} label="Ad Soyad" value={formData.sellerName} onChange={(e) => handleInputChange('sellerName', e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><Person /></InputAdornment> }} required /><TextField sx={{ flex: 1, minWidth: 200 }} label="Telefon" value={formData.sellerPhone} onChange={(e) => handleInputChange('sellerPhone', e.target.value)} placeholder="(5XX) XXX XX XX" InputProps={{ startAdornment: <InputAdornment position="start"><Phone /></InputAdornment> }} required error={!formData.sellerPhone} helperText={!formData.sellerPhone ? "Telefon numarası zorunludur" : ""} /></Box><TextField fullWidth label="E-posta" value={formData.sellerEmail} onChange={(e) => handleInputChange('sellerEmail', e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><Email /></InputAdornment> }} type="email" required /><Alert severity="info"><strong>Önemli:</strong> İlanınız yayına alınmadan önce moderatörlerimiz tarafından incelenecektir. Onay sürecinde e-posta veya telefon ile bilgilendirileceksiniz.</Alert></Stack>);
      default: return 'Bilinmeyen adım';
    }
  };

  return (<Box sx={{ width: '100%', p: 3 }}><Typography variant="h4" component="h1" gutterBottom>Vasıta Römorku İlanı Ver</Typography><Stepper activeStep={activeStep} sx={{ mb: 4 }}>{steps.map((label) => (<Step key={label}><StepLabel>{label}</StepLabel></Step>))}</Stepper><Box sx={{ mb: 4 }}>{renderStepContent(activeStep)}</Box><Box sx={{ display: 'flex', flexDirection: 'row', pt: 2 }}><Button color="inherit" disabled={activeStep === 0} onClick={handleBack} sx={{ mr: 1 }}>Geri</Button><Box sx={{ flex: '1 1 auto' }} />{activeStep === steps.length - 1 ? (<Button onClick={() => console.log('Form submitted:', formData)} variant="contained">İlanı Yayınla</Button>) : (<Button onClick={handleNext} variant="contained">İleri</Button>)}</Box></Box>);
};

export default VasitaRomorkForm;
